### ISSUE TITLE
需求建议：模拟器匹配日志添加简单查询

### ISSUE THREAD

**Issue by wangwei1011** [agilean/mock-api#1]
需求建议：模拟器匹配日志添加简单查询
a\增加成功失败查询。点击成功只显示成功匹配请求，失败只显示失败请求。
b\增加接口类型查询。如点击get只列出请求等。

**Comment by ratlsun** [comment]
非常好的建议，已经采纳，会安排进后续开发计划

**Comment by lxbzmy** [comment]
唔，日志量大确实需要这样。

**Comment by zxgjava** [comment]
#匹配日志搜索：
*按匹配情况（匹配成功、匹配失败）搜索
*按请求方法类型（GET、PUT、POST、DELETE）搜索
