### ISSUE TITLE
需求建议：模拟器匹配日志点击可直接进行编辑

### ISSUE THREAD

**Issue by wangwei1011** [agilean/mock-api#2]
需求建议：模拟器匹配日志点击可直接进行编辑
场景操作
1、日志列出成功匹配请求
2、点击，进入该请求编辑界面直接编辑返回内容

目前来说双开窗口调整效率也不错，如果单开窗口必须点击 控制面，具体项目，条目编辑才可以

**Comment by ratlsun** [comment]
采纳

**Comment by lxbzmy** [comment]
命中的规则变成一个链接。

**Comment by zxgjava** [comment]
close #2

**Comment by zxgjava** [comment]
在匹配日志界面直接可以点击编辑成功匹配的规则
![edit-rule-on-hit-page](https://cloud.githubusercontent.com/assets/11919245/19803473/6f51e99e-9d3b-11e6-9c32-1f86ed3ae3e6.png)
